version: '3'
services:
  product-service:
    container_name: productservice
    image: product-app02
    restart: on-failure
    ports:
      - 9002:9090
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql-service
      - coupon-service
  coupon-service:
    container_name: couponservice
    image: coupon-app02
    restart: on-failure
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - 9001:9091
    depends_on:
      - mysql-service
  mysql-service:
    image: mysql
    container_name: docker-mysql
    ports:
      - 6666:3306
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: "%"
    