version: '3.3'
services:
  web:
      image: nginx
      container_name: mywebserver
      networks:
        - webnetwork
      ports:
          - 8080:80
      volumes:
        - type: bind
          source: C:\myvol
          target: /test
networks:
  webnetwork:
    driver: bridge
  dbnetwork:
    driver: bridge
volumes:
  myvol: